import Foundation
import XCTest
@testable import TenXAppCore

final class LocalAssetStorageTests: XCTestCase {
    private struct Harness {
        let rootURL: URL
        let databaseURL: URL
        let database: CockpitDatabase
        let repository: AssetRepository
        let storage: LocalAssetStorage
        let project: BuilderProject
    }

    private func makeHarness() async throws -> Harness {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let databaseURL = root.appendingPathComponent("cockpit.sqlite")
        let assetRootURL = root.appendingPathComponent("assets", isDirectory: true)
        let database = try CockpitDatabase(url: databaseURL)
        let profile = try await ProfileRepository(database: database).loadOrCreateProfile()
        let project = try await ProjectRepository(database: database).createProject(
            userId: profile.id,
            name: "Asset Project"
        )
        let repository = AssetRepository(database: database)
        let storage = LocalAssetStorage(rootURL: assetRootURL, repository: repository)

        addTeardownBlock {
            try? FileManager.default.removeItem(at: root)
        }

        return Harness(
            rootURL: assetRootURL,
            databaseURL: databaseURL,
            database: database,
            repository: repository,
            storage: storage,
            project: project
        )
    }

    func testAssetWriteCreatesFileAndCanReadData() async throws {
        let harness = try await makeHarness()
        let data = Data("hello local asset".utf8)

        let asset = try await harness.storage.writeAsset(
            projectId: harness.project.id,
            kind: .upload,
            filename: "reference.png",
            mimeType: "image/png",
            data: data
        )

        XCTAssertTrue(asset.relativePath.hasPrefix("projects/\(harness.project.id)/uploads/"))
        XCTAssertEqual(asset.sizeBytes, data.count)
        XCTAssertEqual(asset.mimeType, "image/png")

        let url = try await harness.storage.assetURL(for: asset.relativePath)
        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))
        let readData = try await harness.storage.readAsset(relativePath: asset.relativePath)
        XCTAssertEqual(readData, data)
    }

    func testAssetMetadataPersistsInSQLiteWithoutBlobStorage() async throws {
        let harness = try await makeHarness()
        let data = Data("generated bytes".utf8)
        let relativePath = LocalAssetStorage.relativePath(
            projectId: harness.project.id,
            kind: .generated,
            filename: "rendered.png"
        )

        let asset = try await harness.storage.writeAsset(
            projectId: harness.project.id,
            kind: .generated,
            relativePath: relativePath,
            mimeType: "image/png",
            data: data
        )

        let rows = try await harness.database.query("SELECT * FROM assets WHERE id = \(CockpitDatabase.escaped(asset.id));")
        XCTAssertEqual(rows.count, 1)
        XCTAssertEqual(rows.first?["relative_path"], relativePath)
        XCTAssertEqual(rows.first?["mime_type"], "image/png")
        XCTAssertEqual(rows.first?["size_bytes"], String(data.count))
        XCTAssertNotNil(rows.first?["checksum"])
        XCTAssertNil(rows.first?["data"])

        let fetched = try await harness.repository.fetchAssets(projectId: harness.project.id)
        XCTAssertEqual(fetched.map(\.id), [asset.id])
        XCTAssertEqual(fetched.first?.deletedAt, nil)
    }

    func testRelativePathsResolveInsideStorageRootForPortableKinds() throws {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
            .appendingPathComponent("assets", isDirectory: true)
        let projectId = UUID().uuidString

        for kind in [LocalAssetKind.upload, .generated, .preview, .export] {
            let relativePath = LocalAssetStorage.relativePath(
                projectId: projectId,
                kind: kind,
                filename: "\(kind.rawValue).png"
            )
            let url = try LocalAssetStorage.resolvedAssetURL(rootURL: root, relativePath: relativePath)
            XCTAssertTrue(relativePath.hasPrefix("projects/\(projectId)/\(kind.directoryName)/"))
            XCTAssertTrue(url.standardizedFileURL.path.hasPrefix(root.standardizedFileURL.path + "/"))
            XCTAssertFalse(url.path.contains(".."))
        }
    }

    func testPathTraversalAndAbsolutePathsAreRejected() {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
            .appendingPathComponent("assets", isDirectory: true)
        let rejectedPaths = [
            "../outside.png",
            "projects/project/../outside.png",
            "/tmp/outside.png",
            "file:///tmp/outside.png",
            "projects/project/previews//double-slash.png",
            "projects\\project\\previews\\outside.png",
        ]

        for path in rejectedPaths {
            XCTAssertThrowsError(try LocalAssetStorage.resolvedAssetURL(rootURL: root, relativePath: path), path)
        }
    }

    func testOfflineReloadReadsPersistedFileAndMetadata() async throws {
        let harness = try await makeHarness()
        let data = Data("offline reload".utf8)
        let asset = try await harness.storage.writeAsset(
            projectId: harness.project.id,
            kind: .preview,
            filename: "screen.png",
            mimeType: "image/png",
            data: data
        )

        let reloadedDatabase = try CockpitDatabase(url: harness.databaseURL)
        let reloadedRepository = AssetRepository(database: reloadedDatabase)
        let reloadedStorage = LocalAssetStorage(
            rootURL: harness.rootURL,
            repository: reloadedRepository
        )

        let fetched = try await reloadedStorage.assets(projectId: harness.project.id)
        XCTAssertEqual(fetched.map(\.id), [asset.id])
        let reloadedData = try await reloadedStorage.readAsset(relativePath: asset.relativePath)
        XCTAssertEqual(reloadedData, data)
    }
}
