import Foundation

struct ProductionGuide: Sendable, Equatable {
    let title: String
    let summary: String
    let sections: [ProductionGuideSection]
    let generatedAt: Date

    nonisolated var markdown: String {
        let timestamp = ISO8601DateFormatter().string(from: generatedAt)
        let sectionText = sections.map(\.markdown).joined(separator: "\n\n")
        return """
        \(ProductionGuideBuilder.generatedMarker)
        # PRODUCTION.md

        ## \(title)

        \(summary)

        Generated by 10x on \(timestamp).

        \(sectionText)
        """
    }
}

struct ProductionGuideSection: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let summary: String
    let icon: String
    let modules: [ProductionGuideModule]

    nonisolated var markdown: String {
        let modulesText = modules.map(\.markdown).joined(separator: "\n\n")
        return """
        ## \(title)

        \(summary)

        \(modulesText)
        """
    }
}

struct ProductionGuideModule: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let summary: String
    let bullets: [String]
    let codeBlockLanguage: String?
    let codeBlock: String?

    nonisolated var markdown: String {
        let bulletText = bullets.map { "- \($0)" }.joined(separator: "\n")
        let codeText: String
        if let codeBlock, !codeBlock.isEmpty {
            let language = codeBlockLanguage ?? ""
            codeText = "\n\n```\(language)\n\(codeBlock)\n```"
        } else {
            codeText = ""
        }

        if bulletText.isEmpty {
            return """
            ### \(title)

            \(summary)\(codeText)
            """
        }

        return """
        ### \(title)

        \(summary)

        \(bulletText)\(codeText)
        """
    }
}

struct ProductionChecklistState: Codable, Sendable, Equatable {
    var checkedItemIDs: Set<String>
    var updatedAt: String

    init(
        checkedItemIDs: Set<String> = [],
        updatedAt: String = Self.timestamp()
    ) {
        self.checkedItemIDs = checkedItemIDs
        self.updatedAt = updatedAt
    }

    func isChecked(_ itemID: String) -> Bool {
        checkedItemIDs.contains(itemID)
    }

    mutating func setChecked(_ isChecked: Bool, for itemID: String) {
        if isChecked {
            checkedItemIDs.insert(itemID)
        } else {
            checkedItemIDs.remove(itemID)
        }
        updatedAt = Self.timestamp()
    }

    private static func timestamp() -> String {
        ISO8601DateFormatter().string(from: Date())
    }

    nonisolated static let empty = Self()
}

struct ProductionChecklistSection: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let summary: String
    let items: [ProductionChecklistItem]
}

struct ProductionChecklistItem: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let detail: String
}

enum ProductionChecklistBuilder {
    static func build(
        environmentVariables: [ProjectEnvironmentVariable],
        hasSupabaseIntegration: Bool
    ) -> [ProductionChecklistSection] {
        let secureKeys = ProjectEnvironmentSecurity.sensitiveKeys(from: environmentVariables)
        let providerProxyDetail: String
        if secureKeys.contains("OPENAI_API_KEY") {
            providerProxyDetail = "OpenAI calls no longer run directly from the app. They go through a backend route I control."
        } else if secureKeys.isEmpty {
            providerProxyDetail = "Any future provider key or privileged workflow will live behind infrastructure I control, not in the shipped client."
        } else {
            providerProxyDetail = "Every secret-backed provider call now runs behind infrastructure I control instead of from the shipped app."
        }

        let dataPermissionDetail: String
        if hasSupabaseIntegration {
            dataPermissionDetail = "Supabase auth, row-level security, and storage rules are tested with production-like users before launch."
        } else {
            dataPermissionDetail = "Auth, permissions, and data writes are enforced outside the client with a real trust boundary."
        }

        return [
            ProductionChecklistSection(
                id: "architecture",
                title: "Architecture",
                summary: "Lock in the backend split before you invite real users.",
                items: [
                    ProductionChecklistItem(
                        id: "backend-choice",
                        title: "Backend choice is decided",
                        detail: "I know whether this app uses Vercel, Supabase, or a combination of both."
                    ),
                    ProductionChecklistItem(
                        id: "provider-proxy",
                        title: "Secret-backed features run off-device",
                        detail: providerProxyDetail
                    ),
                    ProductionChecklistItem(
                        id: "public-config",
                        title: "Client config is safe to ship",
                        detail: "Only public endpoints and intentionally ship-safe keys remain in the app bundle."
                    ),
                ]
            ),
            ProductionChecklistSection(
                id: "hardening",
                title: "Hardening",
                summary: "Make failure states, permissions, and operations boring before launch.",
                items: [
                    ProductionChecklistItem(
                        id: "permissions",
                        title: "Auth and data permissions are enforced correctly",
                        detail: dataPermissionDetail
                    ),
                    ProductionChecklistItem(
                        id: "networking",
                        title: "Networking has timeouts and user-facing error states",
                        detail: "Critical requests have timeout behavior, retries where appropriate, and clear recovery UI."
                    ),
                    ProductionChecklistItem(
                        id: "logging",
                        title: "Server-side logging is in place",
                        detail: "I can inspect API errors, provider failures, and important business events after release."
                    ),
                ]
            ),
            ProductionChecklistSection(
                id: "launch",
                title: "Launch",
                summary: "Validate the real production stack and finish the release details.",
                items: [
                    ProductionChecklistItem(
                        id: "preview-cleanup",
                        title: "Preview-only behavior is removed or gated",
                        detail: "Local preview shortcuts, demo credentials, and debug fallbacks cannot leak into the release build."
                    ),
                    ProductionChecklistItem(
                        id: "device-testing",
                        title: "Critical flows are tested on device and TestFlight",
                        detail: "Sign-in, payments, AI actions, uploads, and failure paths work outside the local preview environment."
                    ),
                    ProductionChecklistItem(
                        id: "store-assets",
                        title: "Store metadata and support details are ready",
                        detail: "Screenshots, privacy answers, review notes, legal links, and support contact info are ready for submission."
                    ),
                ]
            ),
        ]
    }
}

enum ProductionGuideBuilder {
    static let generatedMarker = "<!-- Generated by 10x -->"

    static func build(
        projectName: String,
        fileTree: [String: String],
        environmentVariables: [ProjectEnvironmentVariable]
    ) -> ProductionGuide {
        let secureKeys = ProjectEnvironmentSecurity.sensitiveKeys(from: environmentVariables)
        let plainKeys = ProjectEnvironmentSecurity.plainKeys(from: environmentVariables)
        let sourceCount = fileTree.count

        let summary = """
        \(projectName) already gives you the iOS client. To make it production-ready, keep the app thin, move privileged work behind infrastructure you control, and validate the real backend before you ship.
        """

        return ProductionGuide(
            title: "Publishing Guide",
            summary: summary,
            sections: [
                foundationSection(
                    projectName: projectName,
                    sourceCount: sourceCount,
                    secureKeys: secureKeys,
                    plainKeys: plainKeys
                ),
                backendStackSection(),
                hardeningSection(),
                releaseSection(secureKeys: secureKeys, plainKeys: plainKeys),
            ],
            generatedAt: Date()
        )
    }

    private static func foundationSection(
        projectName: String,
        sourceCount: Int,
        secureKeys: [String],
        plainKeys: [String]
    ) -> ProductionGuideSection {
        ProductionGuideSection(
            id: "foundation",
            title: "Production Foundation",
            summary: "Start by being explicit about what the shipped app should do and what should move behind infrastructure.",
            icon: "square.stack.3d.up",
            modules: [
                ProductionGuideModule(
                    id: "generated-app",
                    title: "What You Already Have",
                    summary: "\(projectName) currently has \(sourceCount) generated source file\(sourceCount == 1 ? "" : "s"). Treat this project as the product surface and app shell, not the trust boundary.",
                    bullets: [
                        "The app can own UI, local state, rendering, caching, and requests to services you control.",
                        "`tenx/` contains local 10x metadata and preview support files. It is not production infrastructure.",
                        "`PRODUCTION.md` is the handoff guide for replacing preview assumptions with a real backend.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "runtime-config",
                    title: "What Cannot Live In The App",
                    summary: "Only values that are safe to expose should ship in the binary. Anything that can spend money, access private data, or enforce business rules should stay off-device.",
                    bullets: runtimeConfigBullets(secureKeys: secureKeys, plainKeys: plainKeys),
                    codeBlockLanguage: "env",
                    codeBlock: """
                    PUBLIC_API_BASE_URL=https://api.yourapp.com
                    SUPABASE_URL=https://your-project.supabase.co
                    SUPABASE_PUBLISHABLE_KEY=ship-only-if-rules-are-correct
                    OPENAI_API_KEY=server-only
                    """
                ),
            ]
        )
    }

    private static func backendStackSection() -> ProductionGuideSection {
        ProductionGuideSection(
            id: "stack",
            title: "Local Cockpit",
            summary: "11x keeps auth, data, storage, and secret-backed work local to this machine by default.",
            icon: "shippingbox",
            modules: [
                ProductionGuideModule(
                    id: "sqlite",
                    title: "SQLite",
                    summary: "The default local data store for the single-user cockpit.",
                    bullets: [
                        "All durable state lives in `cockpit.sqlite` inside the app support directory.",
                        "No remote Postgres service, Docker, or managed database is required.",
                        "Backups are the user's responsibility: copy or export the app support folder.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "keychain",
                    title: "Keychain",
                    summary: "Provider secrets and credentials are stored in the OS keychain.",
                    bullets: [
                        "`OPENAI_API_KEY` is stored in the keychain, not in project files or exported data.",
                        "Keychain records are namespaced under `app.kasey.11x` so they do not collide with other apps.",
                        "The OS handles unlock and access control.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "local-export",
                    title: "Local Export",
                    summary: "Projects leave this machine only when you explicitly export them.",
                    bullets: [
                        "Folder exports include generated project files and referenced local assets.",
                        "ZIP exports include the same content in a single archive.",
                        "Exports never include provider secrets or keychain-backed values.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
            ]
        )
    }

    private static func hardeningSection() -> ProductionGuideSection {
        ProductionGuideSection(
            id: "hardening",
            title: "Production Hardening",
            summary: "The production version should survive bad networks, bad inputs, and real user data.",
            icon: "lock.shield",
            modules: [
                ProductionGuideModule(
                    id: "security",
                    title: "Security And Auth",
                    summary: "Enforce permissions in infrastructure you control instead of trusting the client to do the right thing.",
                    bullets: [
                        "Do not trust client conditionals for auth, billing, feature gating, or write permissions.",
                        "Audit every network request and move privileged provider calls behind your backend.",
                        "Remove preview-only shortcuts, seeded demo accounts, and debug-only toggles from release builds.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "operations",
                    title: "Reliability And Observability",
                    summary: "Launch gets easier once errors are visible and recoverable.",
                    bullets: [
                        "Add request timeouts, retry rules where appropriate, and user-facing recovery states.",
                        "Log API failures, provider latency, background job failures, and critical business events server-side.",
                        "Track usage and cost-sensitive actions where they actually happen instead of relying on client guesses.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
            ]
        )
    }

    private static func releaseSection(
        secureKeys: [String],
        plainKeys: [String]
    ) -> ProductionGuideSection {
        _ = secureKeys
        _ = plainKeys
        return ProductionGuideSection(
            id: "release",
            title: "Release Path",
            summary: "11x does not submit to the App Store or manage a hosted release pipeline. Use your own manual workflow.",
            icon: "paperplane",
            modules: [
                ProductionGuideModule(
                    id: "manual-export",
                    title: "Export First",
                    summary: "Export the project locally before moving it to any external system.",
                    bullets: [
                        "Use the local folder or ZIP export to grab the generated project and assets.",
                        "Open the exported project in Xcode and finish any signing, provisioning, or App Store-specific metadata there.",
                        "Secrets and keychain-backed values are not included in exports.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "your-own-release",
                    title: "Use Your Own Release Pipeline",
                    summary: "Submit and distribute through your own Apple Developer account and tooling.",
                    bullets: [
                        "TestFlight, App Store Connect, and notarization are outside 11x's scope.",
                        "Keep screenshots, privacy answers, support contact info, review notes, and legal URLs in your own records.",
                        "Freeze the launch checklist and only submit after the critical items are actually complete.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
            ]
        )
    }

    private static func runtimeConfigBullets(secureKeys: [String], plainKeys: [String]) -> [String] {
        var bullets: [String] = []

        if secureKeys.contains("OPENAI_API_KEY") {
            bullets.append("`OPENAI_API_KEY` is stored in the keychain and is never exported with the project.")
        } else {
            bullets.append("No provider secret is configured. Add one in settings when you are ready to generate against your own endpoint.")
        }

        if plainKeys.contains("OPENAI_BASE_URL") || plainKeys.contains("OPENAI_MODEL") {
            var clientKeys: [String] = []
            if plainKeys.contains("OPENAI_BASE_URL") { clientKeys.append("`OPENAI_BASE_URL`") }
            if plainKeys.contains("OPENAI_MODEL") { clientKeys.append("`OPENAI_MODEL`") }
            bullets.append("Provider metadata configured: \(clientKeys.joined(separator: ", ")). These are safe to keep in the project because they are not secrets.")
        } else {
            bullets.append("No provider metadata is configured. Set `OPENAI_BASE_URL` and `OPENAI_MODEL` in settings or project integrations.")
        }

        bullets.append("If a value can spend money, access private data, or call a provider with elevated privileges, store it in the keychain or an encrypted config file, not in exported project files.")
        return bullets
    }
}
