import Foundation

struct ProductionGuide: Sendable, Equatable {
    let title: String
    let summary: String
    let sections: [ProductionGuideSection]
    let generatedAt: Date

    nonisolated var markdown: String {
        let timestamp = ISO8601DateFormatter().string(from: generatedAt)
        let sectionText = sections.map(\.markdown).joined(separator: "\n\n")
        return """
        \(ProductionGuideBuilder.generatedMarker)
        # PRODUCTION.md

        ## \(title)

        \(summary)

        Generated by 10x on \(timestamp).

        \(sectionText)
        """
    }
}

struct ProductionGuideSection: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let summary: String
    let icon: String
    let modules: [ProductionGuideModule]

    nonisolated var markdown: String {
        let modulesText = modules.map(\.markdown).joined(separator: "\n\n")
        return """
        ## \(title)

        \(summary)

        \(modulesText)
        """
    }
}

struct ProductionGuideModule: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let summary: String
    let bullets: [String]
    let codeBlockLanguage: String?
    let codeBlock: String?

    nonisolated var markdown: String {
        let bulletText = bullets.map { "- \($0)" }.joined(separator: "\n")
        let codeText: String
        if let codeBlock, !codeBlock.isEmpty {
            let language = codeBlockLanguage ?? ""
            codeText = "\n\n```\(language)\n\(codeBlock)\n```"
        } else {
            codeText = ""
        }

        if bulletText.isEmpty {
            return """
            ### \(title)

            \(summary)\(codeText)
            """
        }

        return """
        ### \(title)

        \(summary)

        \(bulletText)\(codeText)
        """
    }
}

struct ProductionChecklistState: Codable, Sendable, Equatable {
    var checkedItemIDs: Set<String>
    var updatedAt: String

    init(
        checkedItemIDs: Set<String> = [],
        updatedAt: String = Self.timestamp()
    ) {
        self.checkedItemIDs = checkedItemIDs
        self.updatedAt = updatedAt
    }

    func isChecked(_ itemID: String) -> Bool {
        checkedItemIDs.contains(itemID)
    }

    mutating func setChecked(_ isChecked: Bool, for itemID: String) {
        if isChecked {
            checkedItemIDs.insert(itemID)
        } else {
            checkedItemIDs.remove(itemID)
        }
        updatedAt = Self.timestamp()
    }

    private static func timestamp() -> String {
        ISO8601DateFormatter().string(from: Date())
    }

    nonisolated static let empty = Self()
}

struct ProductionChecklistSection: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let summary: String
    let items: [ProductionChecklistItem]
}

struct ProductionChecklistItem: Identifiable, Sendable, Equatable {
    let id: String
    let title: String
    let detail: String
}

enum ProductionChecklistBuilder {
    static func build(
        environmentVariables: [ProjectEnvironmentVariable],
        hasSupabaseIntegration: Bool
    ) -> [ProductionChecklistSection] {
        let secureKeys = ProjectEnvironmentSecurity.sensitiveKeys(from: environmentVariables)
        let providerProxyDetail: String
        if secureKeys.contains("OPENAI_API_KEY") {
            providerProxyDetail = "OpenAI calls no longer run directly from the app. They go through a backend route I control."
        } else if secureKeys.isEmpty {
            providerProxyDetail = "Any future provider key or privileged workflow will live behind infrastructure I control, not in the shipped client."
        } else {
            providerProxyDetail = "Every secret-backed provider call now runs behind infrastructure I control instead of from the shipped app."
        }

        let dataPermissionDetail: String
        if hasSupabaseIntegration {
            dataPermissionDetail = "Supabase auth, row-level security, and storage rules are tested with production-like users before launch."
        } else {
            dataPermissionDetail = "Auth, permissions, and data writes are enforced outside the client with a real trust boundary."
        }

        return [
            ProductionChecklistSection(
                id: "architecture",
                title: "Architecture",
                summary: "Lock in the backend split before you invite real users.",
                items: [
                    ProductionChecklistItem(
                        id: "backend-choice",
                        title: "Backend choice is decided",
                        detail: "I know whether this app uses Vercel, Supabase, or a combination of both."
                    ),
                    ProductionChecklistItem(
                        id: "provider-proxy",
                        title: "Secret-backed features run off-device",
                        detail: providerProxyDetail
                    ),
                    ProductionChecklistItem(
                        id: "public-config",
                        title: "Client config is safe to ship",
                        detail: "Only public endpoints and intentionally ship-safe keys remain in the app bundle."
                    ),
                ]
            ),
            ProductionChecklistSection(
                id: "hardening",
                title: "Hardening",
                summary: "Make failure states, permissions, and operations boring before launch.",
                items: [
                    ProductionChecklistItem(
                        id: "permissions",
                        title: "Auth and data permissions are enforced correctly",
                        detail: dataPermissionDetail
                    ),
                    ProductionChecklistItem(
                        id: "networking",
                        title: "Networking has timeouts and user-facing error states",
                        detail: "Critical requests have timeout behavior, retries where appropriate, and clear recovery UI."
                    ),
                    ProductionChecklistItem(
                        id: "logging",
                        title: "Server-side logging is in place",
                        detail: "I can inspect API errors, provider failures, and important business events after release."
                    ),
                ]
            ),
            ProductionChecklistSection(
                id: "launch",
                title: "Launch",
                summary: "Validate the real production stack and finish the release details.",
                items: [
                    ProductionChecklistItem(
                        id: "preview-cleanup",
                        title: "Preview-only behavior is removed or gated",
                        detail: "Local preview shortcuts, demo credentials, and debug fallbacks cannot leak into the release build."
                    ),
                    ProductionChecklistItem(
                        id: "device-testing",
                        title: "Critical flows are tested on device and TestFlight",
                        detail: "Sign-in, payments, AI actions, uploads, and failure paths work outside the local preview environment."
                    ),
                    ProductionChecklistItem(
                        id: "store-assets",
                        title: "Store metadata and support details are ready",
                        detail: "Screenshots, privacy answers, review notes, legal links, and support contact info are ready for submission."
                    ),
                ]
            ),
        ]
    }
}

enum ProductionGuideBuilder {
    static let generatedMarker = "<!-- Generated by 10x -->"

    static func build(
        projectName: String,
        fileTree: [String: String],
        environmentVariables: [ProjectEnvironmentVariable]
    ) -> ProductionGuide {
        let secureKeys = ProjectEnvironmentSecurity.sensitiveKeys(from: environmentVariables)
        let plainKeys = ProjectEnvironmentSecurity.plainKeys(from: environmentVariables)
        let sourceCount = fileTree.count

        let summary = """
        \(projectName) already gives you the iOS client. To make it production-ready, keep the app thin, move privileged work behind infrastructure you control, and validate the real backend before you ship.
        """

        return ProductionGuide(
            title: "Publishing Guide",
            summary: summary,
            sections: [
                foundationSection(
                    projectName: projectName,
                    sourceCount: sourceCount,
                    secureKeys: secureKeys,
                    plainKeys: plainKeys
                ),
                backendStackSection(),
                hardeningSection(),
                releaseSection(secureKeys: secureKeys, plainKeys: plainKeys),
            ],
            generatedAt: Date()
        )
    }

    private static func foundationSection(
        projectName: String,
        sourceCount: Int,
        secureKeys: [String],
        plainKeys: [String]
    ) -> ProductionGuideSection {
        ProductionGuideSection(
            id: "foundation",
            title: "Production Foundation",
            summary: "Start by being explicit about what the shipped app should do and what should move behind infrastructure.",
            icon: "square.stack.3d.up",
            modules: [
                ProductionGuideModule(
                    id: "generated-app",
                    title: "What You Already Have",
                    summary: "\(projectName) currently has \(sourceCount) generated source file\(sourceCount == 1 ? "" : "s"). Treat this project as the product surface and app shell, not the trust boundary.",
                    bullets: [
                        "The app can own UI, local state, rendering, caching, and requests to services you control.",
                        "`tenx/` contains local 10x metadata and preview support files. It is not production infrastructure.",
                        "`PRODUCTION.md` is the handoff guide for replacing preview assumptions with a real backend.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "runtime-config",
                    title: "What Cannot Live In The App",
                    summary: "Only values that are safe to expose should ship in the binary. Anything that can spend money, access private data, or enforce business rules should stay off-device.",
                    bullets: runtimeConfigBullets(secureKeys: secureKeys, plainKeys: plainKeys),
                    codeBlockLanguage: "env",
                    codeBlock: """
                    PUBLIC_API_BASE_URL=https://api.yourapp.com
                    SUPABASE_URL=https://your-project.supabase.co
                    SUPABASE_PUBLISHABLE_KEY=ship-only-if-rules-are-correct
                    OPENAI_API_KEY=server-only
                    """
                ),
            ]
        )
    }

    private static func backendStackSection() -> ProductionGuideSection {
        ProductionGuideSection(
            id: "stack",
            title: "Recommended Backend Stack",
            summary: "Most teams only need a small amount of backend code. Supabase Edge Functions are part of the supported production path, so the decision is where auth, secrets, and durable data should live.",
            icon: "shippingbox",
            modules: [
                ProductionGuideModule(
                    id: "vercel",
                    title: "Choose Vercel When",
                    summary: "Vercel is the simplest choice when you mainly need server functions, webhook handling, scheduled jobs, or a thin API layer in front of vendors.",
                    bullets: [
                        "You want fast deployment for API routes, AI proxy endpoints, Stripe webhooks, or cron-style jobs.",
                        "You already have a Next.js site or expect to add one soon.",
                        "Your database needs are light or already handled elsewhere.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "supabase",
                    title: "Choose Supabase When",
                    summary: "Supabase is the better default when auth, relational data, storage, permissions, and Edge Functions are core product requirements.",
                    bullets: [
                        "You need user accounts, Postgres tables, file uploads, admin views, realtime data, or named backend functions.",
                        "You want auth, database, storage, SQL migrations, and server-side logic in one place.",
                        "You are comfortable treating publishable client keys as public and enforcing access with Row Level Security and function auth.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "managed-backend",
                    title: "Use 10x Backend When",
                    summary: "The managed Backend workspace is the right path when you want 10x to scaffold and operate named Supabase Edge Functions for secret-backed API work.",
                    bullets: [
                        "`supabase/functions/<name>/index.ts` is the source of truth for each named endpoint.",
                        "Backend-only secrets belong in Backend and sync to Supabase. Do not ship them as client runtime variables.",
                        "If Backend deploys are blocked, treat that as a Supabase project plan or capability issue, not a reason to move secrets back into the app.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "both",
                    title: "Use Both When",
                    summary: "Supabase plus Vercel is still useful when you also need a web app or server surfaces outside Supabase, but it is no longer the only production path.",
                    bullets: [
                        "Use Supabase for auth, Postgres, storage, user-owned data, and any Edge Functions that sit close to that data model.",
                        "Use Vercel for a Next.js site, vendor webhooks that already live there, or jobs that should stay outside Supabase.",
                        "Keep the app talking to the smallest API surface that supports the real user flows.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
            ]
        )
    }

    private static func hardeningSection() -> ProductionGuideSection {
        ProductionGuideSection(
            id: "hardening",
            title: "Production Hardening",
            summary: "The production version should survive bad networks, bad inputs, and real user data.",
            icon: "lock.shield",
            modules: [
                ProductionGuideModule(
                    id: "security",
                    title: "Security And Auth",
                    summary: "Enforce permissions in infrastructure you control instead of trusting the client to do the right thing.",
                    bullets: [
                        "Do not trust client conditionals for auth, billing, feature gating, or write permissions.",
                        "Audit every network request and move privileged provider calls behind your backend.",
                        "Remove preview-only shortcuts, seeded demo accounts, and debug-only toggles from release builds.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "operations",
                    title: "Reliability And Observability",
                    summary: "Launch gets easier once errors are visible and recoverable.",
                    bullets: [
                        "Add request timeouts, retry rules where appropriate, and user-facing recovery states.",
                        "Log API failures, provider latency, background job failures, and critical business events server-side.",
                        "Track usage and cost-sensitive actions where they actually happen instead of relying on client guesses.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
            ]
        )
    }

    private static func releaseSection(
        secureKeys: [String],
        plainKeys: [String]
    ) -> ProductionGuideSection {
        var beforeTestFlight = [
            "Run the app against the real production-style backend instead of preview-only assumptions.",
            "If you use Backend, deploy the named Supabase Edge Functions you depend on and smoke-test them before inviting testers.",
            "Confirm backend secrets are synced remotely before TestFlight instead of relying on local-only configuration.",
            "Test sign-in, purchases, uploads, AI calls, and failure states on physical devices and TestFlight.",
            "Confirm analytics, logs, and crash reporting are visible before inviting external testers.",
        ]
        if secureKeys.contains("OPENAI_API_KEY") {
            beforeTestFlight.insert("Move OpenAI traffic behind your backend before TestFlight distribution.", at: 0)
        }
        if plainKeys.contains("SUPERWALL_PUBLIC_API_KEY") {
            beforeTestFlight.append("For Superwall, remove preview-only audience targeting, confirm App Store Connect product IDs, and verify real TestFlight or sandbox purchases before launch.")
        }

        return ProductionGuideSection(
            id: "release",
            title: "Release Path",
            summary: "Use TestFlight as the last systems check, then finish the App Store-specific details.",
            icon: "paperplane",
            modules: [
                ProductionGuideModule(
                    id: "testflight",
                    title: "Before TestFlight",
                    summary: "Invite testers only after the production stack is real enough to learn from.",
                    bullets: beforeTestFlight,
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
                ProductionGuideModule(
                    id: "app-store",
                    title: "Before The App Store",
                    summary: "Finish the release paperwork while the build is still fresh in your head.",
                    bullets: [
                        "Prepare screenshots, privacy answers, support contact info, review notes, and legal URLs.",
                        "Write down the simplest explanation of your backend architecture for future maintenance and onboarding.",
                        "Freeze the launch checklist and only submit after the critical items are actually complete.",
                    ],
                    codeBlockLanguage: nil,
                    codeBlock: nil
                ),
            ]
        )
    }

    private static func runtimeConfigBullets(secureKeys: [String], plainKeys: [String]) -> [String] {
        var bullets: [String] = []

        if secureKeys.isEmpty {
            bullets.append("No secret-like environment variables are configured right now, which is a good time to decide what must stay off-device before launch.")
        } else {
            bullets.append("Hosted keys configured: \(secureKeys.map { "`\($0)`" }.joined(separator: ", ")). 10x syncs them to Supabase secrets so they stay out of shipped client code and project files.")
        }

        if plainKeys.isEmpty {
            bullets.append("No public config keys are configured right now.")
        } else {
            bullets.append("Public config keys configured: \(plainKeys.map { "`\($0)`" }.joined(separator: ", ")). Keep these in the client only if they are intentionally safe to ship.")
        }

        if plainKeys.contains("SUPERWALL_PUBLIC_API_KEY") {
            bullets.append("`SUPERWALL_PUBLIC_API_KEY` is client-safe, but Superwall still needs production handoff: tighten campaign audiences, confirm store products, and verify release purchase behavior before shipping.")
        }

        bullets.append("If a value can spend money, access private data, or call a provider with elevated privileges, move it behind your backend.")
        return bullets
    }
}
